fs.tomcat:
  image: tianon/true
  volumes:
    - ./srv/logs:/opt/tomcat/logs

fs.db:
  image: tianon/true
  volumes:
    - ./mysql_datadir:/var/lib/mysql
    - ./mysql_autoload:/docker-entrypoint-initdb.d:ro

db:
  image: mysql:5.6
  container_name: shared_seqdb_database
  env_file: .env
  ports:
   - 13306:3306
  volumes_from:
    - fs.db

tomcat:
  image: dina/seqdb:v3.189
  env_file: .env
  environment:
    - VIRTUAL_HOST=seqdb.nrm.se
    - VIRTUAL_PORT=8080
  links:
   - db:db
  volumes_from:
  - fs.tomcat
